<?php
if ( ! function_exists('acf_add_local_field_group') ) return;
$front_id = get_option('page_on_front') ?: (is_front_page() ? get_the_ID() : 0);
acf_add_local_field_group([
    'key'      => 'group_js_final_v3',
    'title'    => '🚀 JUMPSEAT ADMIN (DINÁMICO)',
    'location' => [[ ['param' => 'page_type', 'operator' => '==', 'value' => 'front_page'] ]],
    'fields'   => [
        ['key'=>'f_g_logo', 'label'=>'Logo Agencia', 'name'=>'agency_logo', 'type'=>'image', 'return_format'=>'url'],
        ['key'=>'f_tab_nav', 'label'=>'1. Menú Header', 'type'=>'tab'],
        ['key'=>'f_m1_l', 'label'=>'Item 1: Texto', 'name'=>'m1_label', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m1_u', 'label'=>'Item 1: URL',    'name'=>'m1_url',   'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m2_l', 'label'=>'Item 2: Texto', 'name'=>'m2_label', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m2_u', 'label'=>'Item 2: URL',    'name'=>'m2_url',   'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m3_l', 'label'=>'Item 3: Texto', 'name'=>'m3_label', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m3_u', 'label'=>'Item 3: URL',    'name'=>'m3_url',   'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m4_l', 'label'=>'Item 4: Texto', 'name'=>'m4_label', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m4_u', 'label'=>'Item 4: URL',    'name'=>'m4_url',   'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m5_l', 'label'=>'Item 5: Texto', 'name'=>'m5_label', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_m5_u', 'label'=>'Item 5: URL',    'name'=>'m5_url',   'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_tab_flights', 'label'=>'2. Flight Board', 'type'=>'tab'],
        ['key'=>'f_fb_headline', 'label'=>'Título Sección', 'name'=>'fb_title', 'type'=>'text', 'default_value'=>'B2B SUCCESS IS IN THE AIR'],
        ['key'=>'f_v1_t', 'label'=>'V1: Hora', 'name'=>'v1_time', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v1_d', 'label'=>'V1: Destino', 'name'=>'v1_dest', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v1_g', 'label'=>'V1: Puerta', 'name'=>'v1_gate', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v2_t', 'label'=>'V2: Hora', 'name'=>'v2_time', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v2_d', 'label'=>'V2: Destino', 'name'=>'v2_dest', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v2_g', 'label'=>'V2: Puerta', 'name'=>'v2_gate', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v3_t', 'label'=>'V3: Hora', 'name'=>'v3_time', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v3_d', 'label'=>'V3: Destino', 'name'=>'v3_dest', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v3_g', 'label'=>'V3: Puerta', 'name'=>'v3_gate', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v4_t', 'label'=>'V4: Hora', 'name'=>'v4_time', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v4_d', 'label'=>'V4: Destino', 'name'=>'v4_dest', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_v4_g', 'label'=>'V4: Puerta', 'name'=>'v4_gate', 'type'=>'text', 'wrapper'=>['width'=>'33%']],
        ['key'=>'f_tab_svc', 'label'=>'3. Servicios (Acordeón)', 'type'=>'tab'],
        ['key'=>'f_svc_h1', 'label'=>'Título Principal', 'name'=>'about_heading', 'type'=>'text'],
        ['key'=>'f_svc_h2', 'label'=>'Título Acento', 'name'=>'about_heading2', 'type'=>'text'],
        ['key'=>'f_svc_desc', 'label'=>'Descripción', 'name'=>'about_description', 'type'=>'textarea'],
        ['key'=>'f_s1_t', 'label'=>'S1: Título', 'name'=>'s1_title', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s1_d', 'label'=>'S1: Descripción', 'name'=>'s1_desc', 'type'=>'textarea', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s2_t', 'label'=>'S2: Título', 'name'=>'s2_title', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s2_d', 'label'=>'S2: Descripción', 'name'=>'s2_desc', 'type'=>'textarea', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s3_t', 'label'=>'S3: Título', 'name'=>'s3_title', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s3_d', 'label'=>'S3: Descripción', 'name'=>'s3_desc', 'type'=>'textarea', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s4_t', 'label'=>'S4: Título', 'name'=>'s4_title', 'type'=>'text', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_s4_d', 'label'=>'S4: Descripción', 'name'=>'s4_desc', 'type'=>'textarea', 'wrapper'=>['width'=>'50%']],
        ['key'=>'f_tab_cases', 'label'=>'4. Case Studies', 'type'=>'tab'],
        ['key'=>'f_cs_line1', 'label'=>'Título Línea 1', 'name'=>'cases_heading_white', 'type'=>'text'],
        ['key'=>'f_cs_line2', 'label'=>'Título Línea 2', 'name'=>'cases_heading_accent', 'type'=>'text'],
        ['key'=>'f_cs1_img', 'label'=>'C1: Imagen', 'name'=>'cs1_image', 'type'=>'image', 'return_format'=>'url'],
        ['key'=>'f_cs1_ty',  'label'=>'C1: Título Amarillo', 'name'=>'cs1_title_yellow', 'type'=>'text'],
        ['key'=>'f_cs1_di',  'label'=>'C1: Desc. Imagen', 'name'=>'cs1_desc_img', 'type'=>'textarea'],
        ['key'=>'f_cs1_pt',  'label'=>'C1: Panel Título', 'name'=>'cs1_panel_title', 'type'=>'text'],
        ['key'=>'f_cs1_pb',  'label'=>'C1: Panel Cuerpo', 'name'=>'cs1_panel_body', 'type'=>'textarea'],
        ['key'=>'f_cs1_u',   'label'=>'C1: URL', 'name'=>'cs1_url', 'type'=>'text'],
        ['key'=>'f_tab_foot', 'label'=>'5. Footer', 'type'=>'tab'],
        ['key'=>'f_f_addr', 'label'=>'Dirección', 'name'=>'footer_address', 'type'=>'text'],
        ['key'=>'f_f_ph', 'label'=>'Teléfono', 'name'=>'footer_phone', 'type'=>'text'],
        ['key'=>'f_f_em', 'label'=>'Email', 'name'=>'footer_email', 'type'=>'text'],
        ['key'=>'f_f_li', 'label'=>'LinkedIn URL', 'name'=>'footer_linkedin', 'type'=>'url'],
        ['key'=>'f_tab_contact', 'label'=>'6. Contacto & CEO', 'type'=>'tab'],
        ['key'=>'f_ceo_img', 'label'=>'Foto CEO', 'name'=>'ceo_photo', 'type'=>'image', 'return_format'=>'url'],
        ['key'=>'f_ceo_em',  'label'=>'Email CEO', 'name'=>'ceo_email', 'type'=>'text'],
        ['key'=>'f_ceo_tg',  'label'=>'Tagline CEO', 'name'=>'ceo_tagline', 'type'=>'text'],
        ['key'=>'f_ceo_txt', 'label'=>'Texto CEO', 'name'=>'ceo_text', 'type'=>'textarea'],
        ['key'=>'f_team_u',  'label'=>'URL Meet the Team', 'name'=>'team_url', 'type'=>'text'],
    ],
]);
